### ISSUE TITLE
Make CrateDB Kubernetes Operator Open Source

### ISSUE THREAD

**Issue by MarkusH** [crate/crate-operator#63]
One of Crate.io's philosophies is supporting and fostering the Open Source community. As part of that we want to publish the CrateDB Kubernetes Operator. This ticket is to track the tasks that need to be done to get us there.

- [x] We will use [AGPL](https://choosealicense.com/licenses/agpl-3.0/) (#65)
- [x] Ensure a license header is present in each file (#65)
- [x] Ensure the license is set in `setup.py` (#65)
- [x] Ensure the license is set in `Dockerfile` (#65)
- [x] Ensure we have a code of conduct linked (#66)
- [x] Ensure we have a good contribution guide (#70)
- [x] Make repo public
